# Generated by Django 3.0.3 on 2020-03-03 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distancia',
            fields=[
                ('codigo', models.IntegerField(verbose_name='Codigo', primary_key=True,)),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('terreno', models.CharField(verbose_name='Terreno', max_length=20)),
                ('area', models.PositiveIntegerField(verbose_name='Area')),
            ],
        ),
    ]
